### PR TITLE
2021 update

### PR DESCRIPTION
**Pull request by andrewwschreiber**
I ran the 2021 data through the build and things worked well. I changed the code in the core and household builds to be a bit more agnostic on calibrated years (only logistical code in the core build and a few bounds are changed in the household build). Note that I did not change the name of "windc_base.gdx"  to "windc_base_2021.gdx" throughout the build. Also needed to add a bit to some household datasets to accomodate the changes. So, in order to rerun this, the data directory needs to be updated.

Also, there is a directory called "compare_versions" which is just to run some basic comparisons between old and new datasets. This shouldn't be included in the final build. Left it there in case you're interested in looking, but can be removed before completing the pull request.

### CODE REVIEW

**Comment by mitchphillipson** [comment]
Thanks Drew. I'll go through this either later today or tomorrow. I think it's useful to keep the comparison directory, I'm sure people will be curious. I did all the comparisons in Python and was very confused for a while!

**Comment by andrewwschreiber** [comment]
Okay, let me make a few more changes so that the comparisons are easy to run. I'll make one more commit today and also link the needed data here. If you target tomorrow for a review, I think that would be perfect. Thanks.

**Comment by mitchphillipson** [comment]
I'm getting an error in line 706 of hhcalib.gms

```
$if %hhdata% == "cps" INTEREST.UP(r,h) = 1.25 * household_shares(r,h,'cap') * cap_own0 * sum((s,rr), kd0(rr,s));
```

There are many errors, but they are all the same

```
**** Matrix error - illegal level value
INTEREST(AL,hh1)   (.LO, .L, .UP = NA, NA, NA)
```

I'm still exploring the issue

**Comment by mitchphillipson** [comment]
> Okay, let me make a few more changes so that the comparisons are easy to run. I'll make one more commit today and also link the needed data here. If you target tomorrow for a review, I think that would be perfect. Thanks.

I realized this may be more annoying than it's worth and I don't think worth it

**Comment by mitchphillipson** [comment]
I think I found the issue, I see `cap_own0` is NaN. I'm loading in Python to better explore things.

Still tracing it down.

**Comment by andrewwschreiber** [comment]
> I'm getting an error in line 706 of hhcalib.gms
> 
> ```
> $if %hhdata% == "cps" INTEREST.UP(r,h) = 1.25 * household_shares(r,h,'cap') * cap_own0 * sum((s,rr), kd0(rr,s));
> ```
> 
> There are many errors, but they are all the same
> 
> ```
> **** Matrix error - illegal level value
> INTEREST(AL,hh1)   (.LO, .L, .UP = NA, NA, NA)
> ```
> 
> I'm still exploring the issue

You need an updated data file -- the cap_own0_ has NA values from 2017-2021 in the original one. I'll send you the file now. Put it in the data/household/cps.

**Comment by andrewwschreiber** [comment]
[windc_vs_nipa_domestic_capital.csv](https://github.com/uw-windc/windc_build/files/12609620/windc_vs_nipa_domestic_capital.csv)

**Comment by mitchphillipson** [comment]
Bingo. 

After this release is out getting the data synced properly is the next step.

**Comment by mitchphillipson** [comment]
I added a few commits to ensure compatibility with GTAPWiNDC.

**Comment by andrewwschreiber** [comment]
awesome -- do you need anything else from me?

**Comment by mitchphillipson** [comment]
I don't think so (other than household documentation). This is pretty great. I've gotten everything to run. I'll merge this later today then update the other branches (gravity and bluenote) to make them consistent.

**Comment by mitchphillipson** [comment]
I saw that. I think that's fine and I can point people to that specific
branch.

**Review by mitchphillipson — APPROVED** [review]

**Pull request merged**
