### PR TITLE
Edits to proposed version 2.0

### PR DESCRIPTION
**Pull request by andrewwschreiber**
Here are proposed edits to the build. Two somewhat significant changes include:

1) inclusion of a production tax rate on output (ty0)
2) restriction of used and scrap sectoral output in the national recalibration routine

Other smaller bug changes:

1) improved the consistency of the labor value share in gspshare.gms (Martha, it may be useful to compare these new numbers with your older plots)
2) changed carrot operator in data/set declarations to work with older versions of the GAMS
3) removed extraneous build.gms, disagg.gms and recalibrate.gms from build_files subdirectory
4) scaled data to be in billions of dollars rather than 10s of billions
5) fixed read error in the nass.gms file
6) clean up code at the end of recalibrate didn't work -- was removed

Things to check on still:

1) bluenote.gms errors in 2015?

I think this covers the changes I made. Let me know if anything else is needed.

### CODE REVIEW

**Comment by andrewwschreiber** [comment]
cool. was your requested change regarding the GDX file? forgot to take that out.

**Comment by boxblox** [comment]
sorry drew, im learning the details of pull requests.  can you remove the GDX file and the org file?  I'd like to keep the master branch pretty lean.

**Comment by andrewwschreiber** [comment]
i've already removed the org file in what was submitted as a pull request. I can update the request without the gdx file.

**Comment by boxblox** [comment]
great thanks

**Comment by andrewwschreiber** [comment]
okay, done.

**Pull request merged**
